[package]
name = "tage_flow"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["std", "derive"], default-features = false }

tage_core = { path = "../tage_core" }
